# name: '20191003-co-culture'
date: '2019-10-03 00:00:00'
# environment:
  # Paths should be set dynamically based on grid
  # path_formats: 'get_default_path_formats("1_XY01_{tile:05d}_Z{z:03d}_CH{channel:d}.tif")'
acquisition:
  # CH1=Cy5 (DRAQ7 red for any dead cells)
  # CH2=Hoechst
  # CH3=brightfield
  per_cycle_channel_names: [Cy5, DAPI, BF]
  channel_names: [DRAQ7, HOECHST, BF]
  emission_wavelengths: [670, 525, 425]
  axial_resolution: 20000.0 # 20um step
  lateral_resolution: 377.442
  magnification: 20
  num_cycles: 1
  numerical_aperture: 0.75
  objective_type: air
  region_names: [Region1]
  region_height: 11
  region_width: 3
  tile_height: 1008
  tile_overlap_x: 576
  tile_overlap_y: 432
  tile_width: 1344
  tiling_mode: snake
  # num_z_planes: 0 # Must be specified per-experiment
operator:
  - extract:
      name: best_z_segm
      channels:
        - proc_HOECHST
        - proc_ICYTE
        - proc_SYTOX
        - proc_BF
        - cyto_cell_boundary
  - montage: {name: best_z_segm, extract_name: best_z_segm}
analysis:
  - aggregate_cytometry_statistics: {mode: best_z_plane}
  - cellprofiler_quantification: {export_csv: true, export_db: true}
processor:
  args:
    gpus: [0,1]
    run_spectral_unmixing: false
    run_deconvolution: false
    run_best_focus: true
    run_cytometry: true
  tile_generator: {raw_file_type: keyence_mixed}
  best_focus: {channel: HOECHST}
  deconvolution: {n_iter: 10, scale_factor: .75, channels: [HOECHST, ICYTE, SYTOX]}
  cytometry:
    # Up-sample to standard image size
    # target_shape: [1008, 1344]
    nuclei_channel_name: HOECHST
    quantification_params:
      nucleus_intensity: true
      morphology_features: false
      cell_graph: false
