# Name constructed using conditions and grid
# name: 'sta-00.125-20um-s-XY01'
date: '2019-07-03 00:00:00'
# environment:
  # Paths should be set dynamically based on grid
  # path_formats: 'get_default_path_formats("1_XY01_{tile:05d}_Z{z:03d}_CH{channel:d}.tif")'
acquisition:
  # Red = SYTOX Cy5 CH1 -- Cy5 captured first to avoid photo-bleaching
  # Gray = BF CH2
  # Blue = DAPI CH3
  per_cycle_channel_names: [Cy5, BF, DAPI]
  channel_names: [SYTOX, BF, HOECHST]
  emission_wavelengths: [670, 425, 425]
  axial_resolution: 20000.0 # 20um step
  lateral_resolution: 377.442
  magnification: 20
  num_cycles: 1
  numerical_aperture: 0.75
  objective_type: air
  region_names: [Region1]
  region_height: 9
  region_width: 3
  tile_height: 1008
  tile_overlap_x: 576
  tile_overlap_y: 432
  tile_width: 1344
  tiling_mode: snake
  # num_z_planes: 0 # Must be specified per-experiment
operator:
  - extract:
      name: best_z_segm
      channels:
        - proc_HOECHST
        - proc_BF
        - proc_SYTOX
        - cyto_cell_boundary
  - montage: {name: best_z_segm, extract_name: best_z_segm}
  - extract:
      z: all
      name: segm
      channels:
        - proc_HOECHST
        - proc_BF
        - proc_SYTOX
        - cyto_cell_boundary
  - montage: {name: segm, extract_name: segm}
analysis:
  - aggregate_cytometry_statistics: {mode: best_z_plane}
  - aggregate_cytometry_statistics: {mode: all, variant: allz}
  - cellprofiler_quantification: {export_csv: true, export_db: true}
processor:
  args:
    gpus: [0,1]
    run_spectral_unmixing: false
    run_deconvolution: false
    run_best_focus: true
    run_cytometry: true
  tile_generator: {raw_file_type: keyence_mixed}
  best_focus: {channel: HOECHST}
  deconvolution: {n_iter: 10, scale_factor: .75, channels: [HOECHST, SYTOX]}
  cytometry:
    nuclei_channel_name: HOECHST
    quantification_params:
      nucleus_intensity: true
      morphology_features: false
      cell_graph: false
